### ISSUE TITLE
inline markup suppresses S

### ISSUE THREAD

**Issue by telic** [emmental/isetools#12]
The XMLWriter drops speeches if they are started after the opening of an inline element.

Eg.
```sgml
<work>
<scene n="1">
<bll><s>test</s></bll>
</scene>
</work>
```

is serialized to
```xml
<work>
<scene n="1"/>
<l><bll>test</bll></l>
</work>
```

The proper result should be:
```xml
<work>
<scene n="1"/>
<l><s k="1"><bll>test</bll></s></l>
</work>
```

I've tested this with `BLL`, `R`, and `FOREIGN`, and they all show the same error.

In reality this will most often be seen when inline elements cover multiple lines of IML.

**Comment by emmental** [comment]
done: 7e9074c
