### ISSUE TITLE
inline embed becomes non-inline

### ISSUE THREAD

**Issue by telic** [emmental/isetools#13]
The XMLWriter appears to be making all `iembed`s at the start of their source line into non-inline content, even when followed by inline content.

Eg.
```
<iembed href="test"/> foo
```
becomes
```xml
<iembed href="test"/>
<l>foo</l>
```
instead of the expected
```xml
<l><iembed href="test"/> foo</l>
```

`iembed` should only be non-inline when they are the only non-whitespace content on the IML source line.

**Comment by emmental** [comment]
This was actually already implemented but I'd forgotten to make the change affect empty iembeds.
- dfd007f
