### ISSUE TITLE
HW alignment should not be hoisted to line

### ISSUE THREAD

**Issue by telic** [emmental/isetools#15]
IML markup like this `<L/>Test <HW><RA>hung</RA></HW>` should result in display XML like `<l>Test <hw>hung</hw></l>` (RA inside of HW is dropped).  Right now, the serializer incorrectly adds an `align="right"` attribute to the enclosing line.

See Lr_Q1 near TLN 93 for an example.

**Comment by emmental** [comment]
Is HW the only tag that this applies to?

Currently, alignments are applied to the entire line in which they appear (the closest if it's in something like a bracegroup).  Should lines break if an alignment is met? For example, should `<L/>test <RA>right</RA>` produce `<l>test </l><l align="right">right</l>`? What about something like `<L/><RA>right</RA> <HW>hung</HW>`; should this be one line that's right aligned?

**Comment by telic** [comment]
The current behaviour is correct except where alignment inside an HW is involved.

`RA`, `J`, and `C` tags that open within `HW` should be dropped without effect. Usage anywhere else should change the alignment of the line as a whole, even if the tags only cover part of the line content. Alignment tags never cause line breaks.

We should probably have a validator that warns against wrapping only part of a line's content in an alignment tag, but that's a separate issue.

Some examples:
 * `<L/>test <RA>right</RA>` -> `<l align="right">test right</l>`
 * `<L/><RA>right</RA> <HW>hung</HW>` -> `<l align="right">right <hw>hung</hw></l>`
 * `<L/>one <J>two <HW>three</HW></J>` -> `<l align="justify">one two <hw>three</hw></l>`
 * `<L/>one <HW><C>two</C></HW>` -> `<l>one <hw>two</hw></l>`
 * `<L/>one <HW><C>two</HW></C>` -> `<l>one <hw>two</hw></l>`

**Comment by telic** [comment]
Handling RAs this way is no longer sufficient, so I'm closing the issue. See telic@aec3775e0bc5373fedfec98fac704da505eef571 for an alternate interim solution.
