### ISSUE TITLE
INDENT not serialized correctly

### ISSUE THREAD

**Issue by telic** [emmental/isetools#17]
`INDENT` is not producing the correct display XML output.

This tag is equivalent to adding a `SPACE` with the same @l value at the beginning of every line spanned by the `INDENT`.

Eg. the IML
```
<INDENT l="2">
<L/>test
<L/>test2
</INDENT>
```
is equivalent to the IML
```
<L/><SPACE l="2"/>test
<L/><SPACE l="2"/>test2
```
and should produce the display XML
```
<l><space t="formatting" l="2"/>test</l>
<l><space t="formatting" l="2"/>test2</l>
```

`INDENT` may occur on its own physical line (as in the example above) or inline with the fist line of indented text (eg. `<L/><INDENT l="2">test`). It **does not** trigger output line generation, so either case will produce the same output.

For simplicity of processing, if the `INDENT` occurs inline, output the first space where the `INDENT` is encountered rather than re-ordering it to the front of the line.

The XMLWriter is currently only adding a space to a single line within an `INDENT`, and often seems to be generating a new empty line for this purpose rather than adding it to the existing content...

**Comment by telic** [comment]
It looks like it is generating the space for every line now, but it's still creating a *new* line for it, rather than inserting it at the beginning of each line in many cases.

Eg.  http://internetshakespeare.uvic.ca/exist/apps/isebeta/content/documents/iml/doc_FairEm_M.txt is serialized to http://internetshakespeare.uvic.ca/exist/apps/isebeta/content/documents/display/doc_FairEm_M.xml. The indented sections after TLN 376 end up double-spaced with no indent (because each indenting space generates it's own otherwise blank line).

**Comment by telic** [comment]
Brett has since replaced the INDENTs in the above example with inlined SPACE to work around the bug. The version with INDENT is available in SVN at revision 11736 or earlier.

**Comment by emmental** [comment]
I've fixed indent's behaviour in the following two commits:
d6734b69145ad1eca50431c97ca7ccb8ab2e7064
fffdf716375a7d338ba1d470a3bb25d5809e0c87

Note that the inline example (`<L/><INDENT l="2"/>test`) does not currently work as the schema is not allowing it to be empty. It's an easy fix if you want this to work.

**Comment by telic** [comment]
Sorry, no that was a typo -- the schema is correct. I only meant that the start tag could occur inside a line.
