### ISSUE TITLE
ADD shouldn't always create a line

### ISSUE THREAD

**Issue by telic** [emmental/isetools#18]
When `<ADD/>` occurs on a line without line content or lineation milestones (usually just containing an iembed), the XMLWriter should not create an output line.  Eg.

```
<add wit="Quarto 1"><iembed component="text" href="fragment-sp/doc_Lr_Q1M#qln-384" /></add>
```
should be output as is, **not** like
```xml
<l><add wit="Quarto 1"><iembed component="text" href="fragment-sp/doc_Lr_Q1M#qln-384" /></add></l>
```

Milestones, text, speeches, etc should continue to form lines, eg
```
<add wit="foo">bar</add>
```
should produce
```xml
<l><add wit="foo">bar</add></l>
```

**Comment by emmental** [comment]
My code is currently requiring that iembeds & ilinks be within `<l>` tags. Is this not a requirement? It parses everything inside the `<add>` tag independently (as if it were its own document with a `<work>` tag around it) and if the root element is `<l>`, then the entire `<add>` is wrapped in an `<l>` and the inner one is dropped.

This is a very easy fix if I can simply remove the requirement of `<iembeds>` (and ilinks?) being a child of an `<l>` tag.

**Comment by telic** [comment]
`iembed` does not need to be inline, but `ilink` does.

**Comment by emmental** [comment]
This should now be working for iembeds: a2ad7e2bfff81165d6f779eb74a4c9ead070188c

Does this issue affect any other tags? The current functionality should only force the ADD to be inline if its contents must be inline, so it _should_ be working as long as the conversion works outside of an ADD.

**Comment by telic** [comment]
I'm not aware of any.
