### ISSUE TITLE
allow two-letter lang codes

### ISSUE THREAD

**Issue by telic** [emmental/isetools#5]
The `ForeignValidator` currently only allows ISO-639-3 codes, but it should also allow the simpler ISO-639-1 two-letter codes.

http://www-01.sil.org/iso639-3/iso-639-3_Code_Tables_20160115.zip includes an "iso-639-3_20160115.tab" file that lists both of these codes and their equivalencies.

**Comment by emmental** [comment]
Never mind I'm blind
