### ISSUE TITLE
switch to BCP-47

### ISSUE THREAD

**Issue by telic** [emmental/isetools#6]
To align with XML/TEI standards, we should switch `FOREIGN@lang` to use BCP-47 coding. Basically, these are ISO-639 codes with additional optional refinement flags, eg "en-US".

BCP-47 technically allows many forms that aren't real languages (eg "frungy-bottom"), so we should continue to validate that the beginning language code is a recognized ISO-639 country. I'd suggest splitting `validator.foreign.invalidCode` into two: `validator.foreign.invalidFormat` and `validator.foreign.unrecognizedLanguage`.

Supersedes #5

**Comment by telic** [comment]
Private-use tags should also be allowed (e.g. "x-nonsense")

**Comment by emmental** [comment]
That would be anything that begins with 'x-'?

**Comment by telic** [comment]
Yes, as long as it's valid BCP-47
