### ISSUE TITLE
prepend act/scene to L numbering

### ISSUE THREAD

**Issue by telic** [emmental/isetools#8]
When serializing a DOM to display-xml, `<L/>` numbering should have the act and scene numbers (separated by ".") prepended to make them unique across the file.

E.g. `<L n="22"/>` in act 1 scene 3 would be serialized as `<ms t="l" n="1.3.22"/>`.

E.g. `<L n="0.3"/>` in scene 2 of text without acts would be serialized as `<ms t="l" n="2.0.3"/>` (if it did have acts, the resulting `n` would have 4 dotted parts)

**Comment by emmental** [comment]
Finally committed this change. It's in fix_commits and allchanges.
