### ISSUE TITLE
XMLWriter is CPU-bound on large inputs

### ISSUE THREAD

**Issue by telic** [emmental/isetools#9]
The XMLWriter seems to be getting bogged down on our beta server when processing large-ish texts such as Lr_Q1M or Lr_FM. The conversion runs for about 5 minutes before Cocoon eventually kills it.

I've checked that the Cocoon logic is not to blame by disabling various bits of the conversion XSP. It is definitely the writer step that is taking the time. It also doesn't appear to be memory related, since the Java VisualVM monitoring tool shows Tomcat running at fairly constant memory utilization with more than 250M to spare throughout. It appears that it's simply taking too much CPU effort.

A CPU profile shows most time is spent in `XMLStack.get_all_elements`, so that would be a good place to start looking for ways to optimize it...

![screen shot 2016-11-17 at 15 54 02](https://cloud.githubusercontent.com/assets/301798/20412954/c8bec9fe-acde-11e6-8c5e-068bee39dbb5.png)

**Comment by emmental** [comment]
Finally committed this fix. It's in fix_commits and allchanges.
